name: build
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code coverage
        uses: actions/upload-artifact@v3.1.0
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: build
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: production
      url: http://github-actions-ok.sh
    steps:
      - name: Download the build artifact
        uses: actions/download-artifact@v3.0.1
        with:
         name: build
      - name: Deploy to Surge
        run: npx surge --project '.' --domain github-actions-ok.sh
        env:
         SURG_LOGIN: ${{secrets.SURGE_LOGIN}}
         SURG_TOKEN: ${{secrets.SURGE_TOKEN}}
         
     
     
